MAKEAPPS := rfclient

# For now, fpm.h and fpm_lsp.h are included in the rfclient/ directory, however
# when these headers are standardised in Quagga upstream, we should include
# them directly from the Quagga source path.

include ../Make.rules
